services:
  - type: web
    name: unit6-back # 서비스 이름 (원하는 이름으로 변경 가능)
    env: python
    pythonVersion: 3.9.0 # 사용할 Python 버전 명시
    buildCommand: "pip install -r requirements.txt && python src/manage.py collectstatic --noinput && python src/manage.py migrate"
    startCommand: "gunicorn src.core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true # Render가 자동으로 생성하도록 설정
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false # Render 대시보드에서 수동으로 설정
      - key: AWS_ACCESS_KEY_ID
        sync: false # Render 대시보드에서 수동으로 설정
      - key: AWS_SECRET_ACCESS_KEY
        sync: false # Render 대시보드에서 수동으로 설정
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false # Render 대시보드에서 수동으로 설정
      - key: AWS_S3_REGION_NAME
        value: "ap-northeast-2" # S3 리전
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: KAKAO_CLIENT_ID
        sync: false
      - key: KAKAO_CLIENT_SECRET
        sync: false
      - key: KAKAO_REDIRECT_URI
        sync: false
    autoDeploy: true