# 워크플로우 이름
name: Deploy Django to EC2

# 언제 이 워크플로우를 실행할 것인가?
on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 실행

# 어떤 작업을 수행할 것인가?
jobs:
  deploy:
    # 어떤 환경에서 실행할 것인가?
    runs-on: ubuntu-latest

    # 작업 단계들
    steps:
      # 1. GitHub에 올라온 소스 코드를 내려받음
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. SSH로 EC2에 접속해서 배포 명령어 실행
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}

          # EC2 서버에 접속해서 실행할 명령어들
          script: |
            # 프로젝트 폴더로 이동
            cd /home/ubuntu/Unit6-back
            
            # GitHub에서 최신 소스 코드 가져오기
            git pull origin main
            
            # NVM을 로드해서 node, npm, pm2 명령어 경로를 설정합니다. (pm2 오류 해결)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # venv 안의 pip를 직접 실행하여 패키지를 정확한 위치에 설치합니다. (가상환경 문제 해결)
            venv/bin/pip install -r requirements.txt
            
            # venv 안의 python을 직접 실행하고, 올바른 manage.py 경로를 사용합니다. (manage.py 오류 해결)
            venv/bin/python manage.py migrate
            venv/bin/python manage.py collectstatic --noinput
            
            # PM2로 앱을 중단 없이 재시작
            pm2 reload "my-app"