# 워크플로우 이름
name: Deploy Django to EC2

# 언제 이 워크플로우를 실행할 것인가?
on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 실행

# 어떤 작업을 수행할 것인가?
jobs:
  deploy:
    # 어떤 환경에서 실행할 것인가?
    runs-on: ubuntu-latest

    # 작업 단계들
    steps:
      # 1. GitHub에 올라온 소스 코드를 내려받음
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. SSH로 EC2에 접속해서 배포 명령어 실행
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}        # GitHub Secrets에 등록한 IP
          username: ${{ secrets.EC2_USERNAME }} # GitHub Secrets에 등록한 사용자 이름
          key: ${{ secrets.EC2_PRIVATE_KEY }}   # GitHub Secrets에 등록한 개인키
          
          # EC2 서버에 접속해서 실행할 명령어들
          script: |
            # 프로젝트 폴더로 이동
            cd /home/ubuntu/Unit6-back
            
            # GitHub에서 최신 소스 코드 가져오기
            git pull origin main
            
            # 파이썬 가상환경 활성화
            source venv/bin/activate
            
            # 파이썬 패키지 설치
            pip install -r requirements.txt
            
            # 데이터베이스 변경사항 적용 (마이그레이션)
            python src/manage.py migrate
            
            # 정적 파일 수집 (CSS, JS 등)
            python src/manage.py collectstatic --noinput
            
            # PM2로 앱을 중단 없이 재시작
            pm2 reload "my-app"